# Generated by Django 3.0.2 on 2020-01-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('brand', models.CharField(choices=[('onyx', 'ONYX'), ('inning', 'INNING'), ('gt', 'GT')], default='ONYX', max_length=50)),
                ('pattern', models.CharField(choices=[('301', '301'), ('311', '311'), ('121', '121'), ('104', '104'), ('105', '105'), ('307', '307'), ('123', '123'), ('gT', 'GT')], default='301', max_length=20)),
                ('size', models.CharField(choices=[('1100r20', '1100R20'), ('1000r20', '1000R20'), ('1200r20', '1200R20'), ('900r20', '900R20'), ('825-16', '825-16'), ('725-16', '725-16')], default='1100R20', max_length=20)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('unit_price', models.BigIntegerField()),
                ('credit', models.BigIntegerField()),
                ('debit', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='app.Account')),
            ],
        ),
    ]
